# Generated by Django 5.1 on 2024-10-17 13:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_admin_options_alter_admin_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booked_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
