# Generated by Django 5.1 on 2024-10-17 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_ticket_booked_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booked_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
