# Generated by Django 5.1 on 2024-10-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_admin_id_alter_bus_id_alter_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(default='abcdef', editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
